# Generated by Django 6.0 on 2026-01-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_connects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
