# Generated by Django 6.0 on 2026-01-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_connects', '0002_alter_advertisement_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
