# Generated by Django 6.0 on 2026-01-05 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_connects', '0003_address_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'In Bearbeitung'), ('approved', 'Bestätigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_requests', to='rental_connects.advertisement', verbose_name='Anzeige')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_requests', to='rental_connects.tenant', verbose_name='Mieter')),
            ],
            options={
                'verbose_name': 'Mietanfrage',
                'verbose_name_plural': 'Mietanfragen',
            },
        ),
    ]
